### ISSUE TITLE
Tasks for Backend

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/drf_api_cutback#1]
## Tasks
- [x] create a user with drf
- [x] delete a user with drf
- [x] full CRUD with Profiles-User in DRF
- [x] !! **create Product model**
- [x] ERD create Rating model
- [x] Manual testing
- [ ] create Milestone for Backend
