### ISSUE TITLE
MODELS: Create User Model

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/drf_api_cutback#2]
## Description
Create a User model which inherits from the AbstractUser model

## Tasks
- [x] updated AUTH_USER_MODEL in settings.py
- [x] define email field - blank=False
- [x] register in Admin.py new User model (with UserAdmin)
- [x] use django-signals to connect User with Profile model for creating & delete functionalities
