### ISSUE TITLE
MODELS: Create Product model

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/drf_api_cutback#4]
## Description
Create a fully functional Product model for use in the database. Follow ERD for fields to be included.

## Tasks:
- [x] start the Product app
- [x] register app in settings.py
- [x] use django-money third-party library MoneyField for price field
- [ ] create image fields to work as gallery
